### ISSUE TITLE
Poincare's Section for positive momentum

### ISSUE THREAD

**Issue by PPorras** [PerezHz/TaylorIntegration.jl#71] opened 2019-05-29 21:58 UTC
I am having trouble calculating a Poincare section for a positive momentum. I tried with the example you provided [here](https://perezhz.github.io/TaylorIntegration.jl/stable/root_finding/). The specific portion of the code that gives me problems is:
      
```Julia
function g(t, x, dx)
    px = constant_term(x[3])
    
    if px > zero(px)
        # ...return x
        return x[1]
    else
        #otherwise, discard the crossing
        return nothing
    end
end
```
Since, I got the error:    

```
MethodError: no method matching surfacecrossing(::Taylor1{Float64}, ::Nothing, ::Int64)
Closest candidates are:
  surfacecrossing(::Taylor1{T<:Number}, !Matched::Taylor1{T<:Number}, ::Int64) where T<:Number at /Users/porras/.julia/dev/TaylorIntegration/src/rootfinding.jl:13
```

**Comment by lbenet** [comment] 2019-05-30 17:44
Which version (of Julia and the package) are you using?

**Comment by PPorras** [comment] 2019-05-30 19:54
I am using the `1.0.3` version of `Julia` and the `0.4.1` version of `TaylorIntegration`.

**Comment by lbenet** [comment] 2019-05-31 01:07
What about `TaylorSeries.jl`? I am trying to have the same set up as you have to see if I can reproduce the problem.

**Comment by lbenet** [comment] 2019-05-31 01:08
Note that the documentation was cheated with Julia v1.0, which I guess corresponds to Julia v1.0.3, and there was no problem...

**Comment by lbenet** [comment] 2019-05-31 04:28
So, I've checked it again and I can't reproduce the problem. Everything runs fine for me using Julia 1.0.3, TaylorIntegration v0.4.1, and TaylorSeries v0.8.0. I haven't checked it, but everything should also run without any problem for more recent versions of TaylorSeries.

**Comment by PPorras** [comment] 2019-05-31 18:42
I'm sorry, I realized I wasn't completely clear about my issue.  I got the error from this part of the code:
```Julia
using TaylorIntegration

for i in 1:nconds
    rand1 = rand()
    rand2 = rand()
    x_ini .= x0 .+ 0.005 .* [0.0, sqrt(rand1)*cos(2pi*rand2), 0.0, sqrt(rand1)*sin(2pi*rand2)]
    px!(x_ini, E0)

    tv_i, xv_i, tvS_i, xvS_i, gvS_i = taylorinteg(henonheiles!, g, x_ini, 0.0, 135.0,
        25, 1e-25, maxsteps=30000);
    tvSv[i] = vcat(0.0, tvS_i)
    xvSv[i] = vcat(transpose(x_ini), xvS_i)
    gvSv[i] = vcat(0.0, gvS_i)
end
```

However, it seems that the real problem is the definition of the function:
```Julia
function g(t, x, dx)
    px = constant_term(x[3])
    
    if px > zero(px)
        # ...return x
        return x[1]
    else
        #otherwise, discard the crossing
        return nothing
    end
end
```

If I change `g(t,x,dx)`for  
```Julia
g(t, x, dx)=x[1]
```

The program works

**Comment by lbenet** [comment] 2019-05-31 18:57
I actually checked if I could reproduce the documentation (step by step, copy-pasting what it is written), and I had no problem. That's the reason I gave all the details of the packages that I used. Yet, I know that the definition of `g` is kind of subtle. 

@PerezHz Do you have an idea what is going on here?

**Comment by PerezHz** [comment] 2019-06-05 03:39
Sorry for the late reply... I also was unable to reproduce the problem; it would seem as if the version is lower than 0.4.0, since it can't find a method of `surfacecrossing` which was introduced in 0.4.0 (specifically, those methods were added in #62), are you completely sure your installed version of TaylorIntegration is 0.4.1? Could you please post the output in the REPL of `using Pkg; Pkg.status()`?

**Comment by PPorras** [comment] 2019-06-05 15:48
Yes, of course!

```Julia
Status `~/.julia/environments/v1.0/Project.toml`
  [6e4b80f9] BenchmarkTools v0.4.1
  [7073ff75] IJulia v1.15.2
  [b964fa9f] LaTeXStrings v1.0.3
  [429524aa] Optim v0.18.1
  [58dd65bb] Plotly v0.2.0
  [91a5bcdd] Plots v0.22.5
  [438e738f] PyCall v1.18.5
  [d330b81b] PyPlot v2.7.0
  [92b13dbe] TaylorIntegration v0.4.1+ [`~/.julia/dev/TaylorIntegration`]
  [6aa5eb33] TaylorSeries v0.9.2
```

**Comment by lbenet** [comment] 2019-06-05 21:18
I can't recognize the commit you are in in `TaylorIntegration`, [92b13dbe]. Can you confirm that commit or where did it diverge from master?

**Comment by PerezHz** [comment] 2019-06-05 22:34
I think [92b13dbe] refers to TaylorIntegration's UUID; but still, yes, it looks as if the local used version of TaylorIntegration is not exactly v0.4.1... Since the output of `status` looks like you have dev'd TaylorIntegration, have you tried doing `git checkout v0.4.1` in the dir `~/.julia/dev/TaylorIntegration` and then checking if the problem disappears?

**Comment by lbenet** [comment] 2019-06-05 23:05
You are right, @PerezHz, it does refers to the uuid.

**Comment by PPorras** [comment] 2019-06-06 01:23
Oh, thank you very much.

When I tried `git checkout v0.4.1`, I got `error: pathspec 'v0.4.1' did not match any file(s) known to git.`. 
So, I pulled from `~/.julia/dev/TaylorIntegration` and then I tried doing  `git checkout v0.4.1` and it worked.

However, I don´t know if the pull was the best option.

**Comment by PerezHz** [comment] 2019-06-06 18:25
> So, I pulled from ~/.julia/dev/TaylorIntegration and then I tried doing git checkout v0.4.1 and it worked.

So, just to confirm: has the original issue been solved?

> However, I don´t know if the pull was the best option.

If you keep TaylorIntegration dev'd then probably you will have to update the versions manually as you just did; but if you don't expect to do many fine-tweakings to TaylorIntegration, then perhaps the best option is to remove TaylorIntegration from your Julia environment and reinstall via `using Pkg; Pkg.add("TaylorIntegration")` so that you use registered versions and then updating to new releases doing e.g. `using Pkg; Pkg.update("TaylorIntegration")`

**Comment by lbenet** [comment] 2019-06-06 18:41
Another way is woth `Pkg.free`:

```
(v1.1) pkg> ?free
  free pkg[=uuid] ...

  Free a pinned package pkg, which allows it to be upgraded or downgraded
  again. If the package is checked out (see help develop) then this command
  makes the package no longer being checked out.
```

**Comment by PPorras** [comment] 2019-06-06 20:23
>So, just to confirm: has the original issue been solved?

Yes, It has been solved.

@lbenet and @PerezHz, thank you for your help.

**Comment by lbenet** [comment] 2019-06-06 20:33
Then I close this issue.

**Closed by lbenet** 2019-06-06 20:33 UTC
