### ISSUE TITLE
_allocate_jetcoeffs! can evaluate terms if'd out in ODE function at the ICs when the term values might not be finite

### ISSUE THREAD

**Issue by vram0gh** [PerezHz/TaylorIntegration.jl#163] opened 2023-05-08 04:08 UTC
I have an ODE system where one of the equations is singular at the initial condition.  Accuracy is not critical for this equation, so in the ODE function, it is simply guarded by an `if` statement that sets the output to zero for this component if it is at an initial condition.  With care, this works for the `@taylorize`d version of `_jetcoeffs!`.  However, when `taylorinteg` invokes `_allocate_jetcoeffs!`, it does so at the initial condition and therefore computes the singular term in the process of trying to allocate space.  It is understandable that `_allocate_jetcoeffs!` allocates memory by looking at all branches of the `if` statement, but unfortunately in this case, it fails evaluating `cot(0.0)`.

I'm not sure what the most elegant way to solve this is, but one approach could be a keyword argument for a specific IV vector to be used for `_allocate_jetcoeffs!`.  In a separate solver that leverages `TaylorIntegration.jl`, I use the Taylor coefficients directly from invoking `_jetcoeffs!`, but am able  to work around this problem by perturbing the IVs when I invoke `_allocate_jetcoeffs!`.

ODE function:

```julia
@taylorize function odesys!(primes, dependent, params, independent)
    local γ = params[1]
    local gm1o2 = (γ - 1) / 2
    θ = independent
    δ = dependent[1]
    M = dependent[2]
    r = dependent[3]
    θmδ = θ - δ
    # write this way to be compatible with @taylorize
    zero_const = r * 0
    local nonzero_streamline =
      if (iszero(r))
        false
      elseif (iszero(θmδ))
        false
      else
        true
      end
    Msq = M ^ 2
    sinδ = sin(δ)
    sinθmδ = sin(θmδ)
    # explicit parenthesized two term expressions for @taylorize compatibility
    den = (((sin(θ) * Msq) * sinθmδ) * sinθmδ) - sin(θ)
    primes[1] = ((cos(θmδ) * sinδ) / den)
    primes[2] = (((((-M) * ((gm1o2 * Msq) + 1)) * sinθmδ) * sinδ) / den)
    if (nonzero_streamline)
      primes[3] = (-r * cot(θmδ))
    else
      primes[3] = zero_const
    end
  end
```

And this can be triggered with:
```julia
taylorinteg(odesys!, [deg2rad(5.0), 2.0, 0.0], deg2rad(5.0), deg2rad(20.0), 20, 1e-20, [1.4])
```

**Comment by lbenet** [comment] 2023-05-09 17:32
Hi @vram0gh !
Using current master, I get the following:
```julia
julia> taylorinteg(odesys!, [deg2rad(5.0), 2.0, 0.0], deg2rad(5.0), deg2rad(20.0), 20, 1e-20, [1.4])
┌ Warning: Unable to use the parsed method of `jetcoeffs!` for `odesys!`,
│ despite of having `parse_eqs=true`, due to some internal error.
│ Using `parse_eqs = false`.
└ @ TaylorIntegration ~/.julia/dev/TaylorIntegration/src/explicitode.jl:323
([0.08726646259971647, 0.09477824944806126, 0.10314842084348391, 0.11247470070604355, 0.12286685578239312, 0.13444848084395214, 0.14735905696687565, 0.16175632018996314, 0.177818989682404, 0.1957499192607936, 0.21577975396012164, 0.23817120171689463, 0.26320139435380213, 0.2910758139481391, 0.32158434018785276, 0.34859160981239684, 0.3490658503988659], [0.08726646259971647 2.0 0.0; 0.08034702652656557 2.0001772043208903 0.0; … ; 0.0178681353880151 2.0291947577676153 0.0; 0.017826698222222676 2.0292474464111474 0.0])
```
As the warning indicates, `@taylorize` is not used; is this what you are reporting? Can you provide more details?

**Comment by lbenet** [comment] 2023-05-12 01:35
The issue appears, as you noted, in `_allocate_jetcoeffs!`, but it is related to `cot` rather than the `if`-block, though it also plays certain role. When you use `@taylorize`, there is no information about the values, then in `_allocate_jetcoeffs!` you must include all possible temporal objects, to save memory. In the case of the `if`, one branch yields a trivial allocation, but the other involves `cot(θmδ)`. The first time that function is used, it is for `iszero(θmδ)==true`, so the `cot` is ill-defined. Note that `cot` is computed as `1/tan(θmδ)` (in Base.Math), so a problem occurs in the division. Then, the problem originates actually in the lack of specific method for `cot(t)` in TaylorSeries; the same will arise for `sec(t)`, `csc(t)`, and other "reciprocal" functions.

Solution: Replace `-r * cot(θmδ)` by `-r / tan(θmδ)`.

**Comment by lbenet** [comment] 2023-05-12 01:36
Feel free to close this issue if my previous comment truly solved it.

**Comment by lbenet** [comment] 2023-05-12 20:02
It is indeed worth documenting the fact that `cot` uses `Base.Math`, instead of a native implementation, but it should be in `TaylorSeries.jl`, since the issue is actually from that package.

**Comment by lbenet** [comment] 2023-05-13 15:58
Yes, let us add a new limitation/advice, emphasizing that not all mathematical functions have been implemented, such as `cot`, `sec`, `csc`, and then those functions are treated as external (and actually are not optimized).

**Closed as completed** 2023-05-17 14:49 UTC
