### ISSUE TITLE
/ not defined for HomogeneousPolynomial

### ISSUE THREAD

**Issue by dfcaporale** [PerezHz/TaylorIntegration.jl#132] opened 2021-06-23 18:07 UTC
Hi! 

I tried to calculate the Lyapunov exponents with your code for a system with functions like `tanh` and found the following error. Maybe you have a suggestion.

Consider the next slightly modified Lorenz function example from the [doc](https://perezhz.github.io/TaylorIntegration.jl/latest/lorenz_lyapunov/#lyap_lorenz):

```julia
function lorenz!(dq, q, params, t)
    σ, ρ, β = params
    x, y, z = q
    dq[1] = σ*tanh(y-x)
    dq[2] = x*(ρ-z)-y
    dq[3] = x*y-β*z
    nothing
end
```

Then, the line 

```julia
tv, xv, λv = lyap_taylorinteg(lorenz!, x0, t0, tmax, 28, 1e-20, params; maxsteps=2000000)
```

leads to the Stacktrace:

```julia
/ not defined for HomogeneousPolynomial{Taylor1{Float64}}

Stacktrace:
  [1] error(::String, ::String, ::Type)
    @ Base .\error.jl:42
  [2] no_op_err(name::String, T::Type)
    @ Base .\promotion.jl:395
  [3] /(x::HomogeneousPolynomial{Taylor1{Float64}}, y::HomogeneousPolynomial{Taylor1{Float64}})
    @ Base .\promotion.jl:399
  [4] /(x::HomogeneousPolynomial{Taylor1{Float64}}, y::Int64)
    @ Base .\promotion.jl:324
  [5] tanh!
    @ ~\.julia\packages\TaylorSeries\tGlgp\src\functions.jl:464 [inlined]
  [6] tanh(a::TaylorN{Taylor1{Float64}})
    @ TaylorSeries ~\.julia\packages\TaylorSeries\tGlgp\src\functions.jl:139
  [7] lorenz!(dq::Vector{TaylorN{Taylor1{Float64}}}, q::Vector{TaylorN{Taylor1{Float64}}}, params::Vector{Float64}, t::Taylor1{Float64})
    @ Main .\In[53]:5
  [8] stabilitymatrix!(eqsdiff!::typeof(lorenz!), t::Taylor1{Float64}, x::Vector{Taylor1{Float64}}, δx::Vector{TaylorN{Taylor1{Float64}}}, dδx::Vector{TaylorN{Taylor1{Float64}}}, jac::Matrix{Taylor1{Float64}}, _δv::Vector{TaylorN{Taylor1{Float64}}}, params::Vector{Float64}, jacobianfunc!::Nothing)
    @ TaylorIntegration ~\.julia\packages\TaylorIntegration\hUDy9\src\lyapunovspectrum.jl:26
  [9] lyap_taylorstep!(f!::Function, t::Taylor1{Float64}, x::Vector{Taylor1{Float64}}, dx::Vector{Taylor1{Float64}}, xaux::Vector{Taylor1{Float64}}, δx::Vector{TaylorN{Taylor1{Float64}}}, dδx::Vector{TaylorN{Taylor1{Float64}}}, jac::Matrix{Taylor1{Float64}}, abstol::Float64, _δv::Vector{TaylorN{Taylor1{Float64}}}, varsaux::Array{Taylor1{Float64}, 3}, params::Vector{Float64}, parse_eqs::Bool, jacobianfunc!::Nothing)
    @ TaylorIntegration ~\.julia\packages\TaylorIntegration\hUDy9\src\lyapunovspectrum.jl:184
 [10] lyap_taylorinteg(f!::Function, q0::Vector{Float64}, t0::Float64, tmax::Float64, order::Int64, abstol::Float64, params::Vector{Float64}, jacobianfunc!::Nothing; maxsteps::Int64, parse_eqs::Bool)
    @ TaylorIntegration ~\.julia\packages\TaylorIntegration\hUDy9\src\lyapunovspectrum.jl:267
 [11] top-level scope
    @ .\timing.jl:210 [inlined]
 [12] top-level scope
    @ .\In[56]:0
 [13] eval
    @ .\boot.jl:360 [inlined]
 [14] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
    @ Base .\loading.jl:1094
```

Thanks for the code, and congratulations on your job!

**Comment by lbenet** [comment] 2021-06-24 14:32
Thanks for reporting @dfcaporale ! 

I'm not sure what's going on here at the moment; I have to check it carefully. The reason that `/` is not defined for `HomogenousPolynomial`s is by design, since the division of two `HomogenousPolynomial`s yields a `TaylorN` in general. this could be generalized, but...

**Comment by lbenet** [comment] 2021-06-24 15:44
The problem is in TaylorSeries; see https://github.com/JuliaDiff/TaylorSeries.jl/issues/282.

**Comment by lbenet** [comment] 2021-06-25 01:16
Closing here.

**Closed by lbenet** 2021-06-25 01:16 UTC

**Comment by lbenet** [comment] 2021-06-25 16:47
@dfcaporale Just to let you know that the PR is merged, and a new release is on the way!
